server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        #路由的id，没有固定规则但要求唯一，建议配合服务名
        - id: payment_routh
#          uri: http://localhost:8001 #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/api/getPaymentById/** #断言，路径相匹配的进行路由

        - id: payment_routh2
#          uri: http://localhost:8001 #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/lb/** #断言，路径相匹配的进行路由

eureka:
  instance:
    hostname: cloud-gateway-service
  #服务提供者provider注册进eureka注册列表
  client:
    service-url:
      #表示是否将自己注册进eurekaServer 默认为true
      register-with-eureka: true
      #是否从eurekaServer抓取已有的注册信息 默认为true，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
      fetch-registry: false
    #单机
      defaultZone: http://localhost:7001/eureka/

#ribbon:
#  eureka:
#    enabled: false
