server:
  port: 80


spring:
  application:
    name: cloud-order-service

eureka:
  client:
  #表示是否将自己注册进eurekaServer 默认为true
    register-with-eureka: true
    #是否从eurekaServer抓取已有的注册信息 默认为true，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
#    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/
#      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
#设置feign客户端超时时间（openFeign默认支持ribbon）
#ribbon:
#值得是建立连接后从服务器读取到可用资源所有的时间
#  ReadTimeout: 500
#指的是建立连接所使用的时间。使用于网络状况正常的情况下，两端连接所有时间
#  ConnectTimeout: 500
logging:
  level:
  #feign已什么级别监听哪个接口
    com.pl.springcloud.service: debug

#开启 熔断器
feign:
  hystrix:
    enabled: true


